### PR TITLE
Improve source timeout error handling

### PR DESCRIPTION
**Pull request by tor-oscar**
If the `Source.run/1` function takes longer than `Dataloader.dataloader_timeout/1` it will get killed and the corresponding task will return `{:exit, :timeout}`.

This return value is transformed to `{:error, :timeout}` in `Dataloader.run_tasks/3`.

In `Dataloader.run/1` this is included in the key value pairs passed to `Map.new` and set as the new value of the `:sources` key of the `Dataloader` struct.

This results in the timed out source key value pair in `:sources` to be removed and the key `:error` added with the value `:timeout`.
 which will cause a variety of errors down the line, among them
```
** (RuntimeError) Source does not exist: <timed_out_source_name>

Registered sources are:

[<source_names...> , :error]
```

The above error is misleading and not very helpful to the developer trying to find the cause of the problem. 

This PR intends to preserve the source name key and replace the source implementation with `{:error, :timeout}`instead of replacing the source key value pair with the error key value pair.

It works seamlessly for `Dataloader.get/4` and `Dataloader.get_many/4` as they will simply handle the error tuple as any other error tuple.

It works fine for `pending_batches?` as source that has returned an error does not have any pending batches, ie `false` is a reasonable return value.

It is a little icky with `Dataloader.put/5` since it is currently no perceivable difference between calling it on an errored source and not. The error will not be triggered until `Dataloader.get/4` or `Dataloader.get_many/4` is called.

It is a little icky with `Dataloader.load/4` and `Dataloader.load_many/4` since it is currently no perceivable difference between calling it on an errored source and not. The error will not be triggered until `Dataloader.get/4` or `Dataloader.get_many/4` is called.

Additional changes
 * Added test of the timeout error handling
 * Added test describing the `max_timeout` feature
 * Made the added margin to the timeout configurable to support testing without waiting seconds.

Thoughts?

### CODE REVIEW

**Comment by benwilson512** [comment]
Hi @tor-oscar I do understand the scenario you're talking about, and I think your PR is a good direction. Can you add a test case demonstrating the issue though to prevent future regressions?

**Comment by tor-oscar** [comment]
Sorry for the delay.
Additional changes
 * Added test of the timeout error handling
 * Added test describing the `max_timeout` feature
 * Made the added margin to the timeout configurable to support testing without waiting seconds.

**Comment by tor-oscar** [comment]
@benwilson512 Do you have any further comments on this PR?

**Comment by tor-oscar** [comment]
Sorry for my silence, this has not been very high on my priorities past year.

I think #155 is a better solution with benefits over this PR. No reason to keep this PR up.

**Pull request closed without merging**
