### PR TITLE
Generate id for schemas without primary key

### PR DESCRIPTION
**Pull request by fuelen**
handles a case when embedded schema struct belongs to normal record, like
```
User
  embeds_one(:address, Address)

Address
  belongs_to(:country, Country)
```

### CODE REVIEW

**Comment by fuelen** [comment]
@benwilson512 please let me know whether this approach OK, and you're ready to merge it, so I could add some tests

**Comment by benwilson512** [comment]
Hi @fuelen can you elaborate a bit more? What sort of `Dataloader.load` call does this help with?

**Comment by fuelen** [comment]
Hi @benwilson512 
Sure :slightly_smiling_face:

If we talk in terms of the schema example above, then I do the following GraphQL query
```graphql
{
  users {
    address {
      country { name }
    }
}
```
the `:address` object is defined like this
```elixir
object :address do
  field(:country, :country, resolve: dataloader(MyApp.Geography))
end
```
nothing special, the resolution of :country field is completely handled by dataloader, no custom options.

Let's say we have 2 users. One user doesn't have set a country in his address (country_id is null). I want to remind, that Address is an embedded schema. Because of this, primary key for embedded schema that doesn't have primary keys is always `[]`. It means that `[]` will be used as an id for all Address structs. So, all addresses will fetch the same country. I noticed, that the first write wins, and depending on the order, all users will have the same country from DB or NULL.

**Comment by fuelen** [comment]
Hey @benwilson512 
Could you look into this?

**Comment by benwilson512** [comment]
Hi @fuelen this seems fine, please just add a test.

**Comment by fuelen** [comment]
Added a test

**Comment by fuelen** [comment]
Hi @benwilson512
Could you merge this PR? :slightly_smiling_face:

**Comment by benwilson512** [comment]
Thanks!

**Pull request merged**
